[package]
name = "cpp-gen-in-proc-macro-impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.81", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.32"
quote = "1.0.10"

cc = "1.0.72"
